---
title: "Interest Rates"
author: "John C. Hull"
output:
  pdf_document:
    toc: true
---

# 4.1 Types of rates

## Treasury rates

Treasury rates are the rates an investor earns on Treasury bills and Treasury
bonds. These are instruments used by a government to borrow in its own currency.

## Overnight rates

Banks are required to maintain a certain amount of cash, known as a reserve,
with the central bank. The reserve requirments for a bank at any time depends on
its oustanding assets and liabilities. At the end of a day, some financial
institutions typically have surplus funds in their accounts with the central
bank while others have requirements for funds. This leads to borrowing and
lending overnight.

In the U.S. the central bank is the Federal Reserve and the overnight rate is
called the _federal funds rate_. The weighted average of the rates in brokered
transactions (with weights being determined by the size of the transaction) is
termed the _effective federal funds rate_.

# 4.2 Reference rates

Reference rates are important in financial markets. The parties to transactions
frequently enter into contracts where the future interest rate paid or received
is uncertain, but will be set equal to the value of an agreed reference interest
rate.

The plan is to base reference rates on the following overnight rates:

* __Secured overnight financing rate__ (SOFR) -- U.S.

* __Sterling overnight index average__ (SONIA) -- UK

* __Euro short-term rate__ (ESTER) -- Eurozone

* __Swiss average rate overnight__ (SARON) -- Switzerland

* __Tokyo overnight average rate__ (TONAR) -- Japan

Longer rates such as three-month rates, six-month rates, or one-year rates can
be determined from overnight rates by compounding them daily.

In the case of SOFR, there are assumed to be 360 days per year. SOFR overnight
rate on the $i$th business day of a period is $r_i$ ($1 \le i \le n$) and the
rate applies to $d_i$ days. The (annualized) interest rate for the period is

$$
[(1 + r_1 \hat{d}_1)(1 + r_2 \hat{d}_2)\ldots(1 + r_n \hat{d}_n) - 1]
  \times \frac{360}{D}
$$

# 4.3 The Risk-free rate

The general approach to valuing derivatives involves setting up a riskless
portfolio and arguing that the return on the portfolio should be the risk-free
rate.

Derivatives traders do not use the rates of Treasury bills and Treasury bonds as
risk-free rates because there are tax and regulatory factors that lead to
Treasury rates being artificially low.

For example:

1. Banks are not required to keep capital for investments in Treasury
   instruments, but they are required to keep capital for other very low risk
   instruments.

2. In the United States, Treasury instruments are given favorable tax treatment
   compared with other very low risk instruments because the interest earned by
   investors is not taxed at the state level.

The risk-free reference rates created from overnight rates are the ones used in
valuing derivatives.

# 4.4 Measuring Interest rates

## Compounding formula

For an amount $A$ that is invested for $n$ years at a rate $R$ that is
compounded $m$ times a year, the terminal value of the investment is:

$$
A \left(1 + \frac{R}{m} \right)^{mn}\tag{4.1}
$$

When $m = 1$, the rate is sometimes referred to as the
_equivalent annual interest rate_.

When comparing interest rates of different compounding periods ($m$) we can use
the folowing formula:

$$
A \left(1 + \frac{R_1}{m_1} \right)^{m_1 n}
=A \left(1 + \frac{R_2}{m_2} \right)^{m_2 n}
$$

Solving for $R_2$ we get:

$$
 R_2 = m_2 \left[ \left(1 + \frac{R_1}{m_1} \right)^{m_1 / m_2} - 1 \right]
$$

## Continuous compounding

The _continuous compounding_ formula is

$$
A e^{Rn}\tag{4.2}
$$

Continuous compounding can be thought of as being equivalent to daily
compounding. Compounding a sum of money at a continuously compounded rate $R$
for $n$ years involves multiplying it by $e^{Rn}$. Discounting it at a
continuously compounded rate $R$ for $n$ years involves multiplying by
$e^{-Rn}$.

Suppose that $R_c$ is a rate of interest with continuous compounding and $R_m$
is the equivalent rate with compounding $m$ times per annum. We can derive the
equivalent formulas:

$$
A e^{R_c n} = A \left(1 + \frac{R_m}{m} \right)^{mn}
$$

or

$$
e^{R_c n} = \left(1 + \frac{R_m}{m} \right)^{mn}
$$

We can derive each rate from the other by:

$$
R_c = m \ln{\left(1 + \frac{R_m}{m}\right)}\tag{4.3}
$$

and

$$
R_m = m(e^{R_c / m} - 1)\tag{4.4}
$$

### Example 4.1

Consider an interest rate that is quoted as 10\% per annum with semiannual
compounding. From equation (4.3) with $m = 2$ and $R_m = 0.1$, the equivalent
rate with continuous compounding is

$$
2 \ln{\left(1 + \frac{0.1}{2}\right)} = 0.09758
$$

or 9.758\%

### Example 4.2

Suppose that a lender quotes the interest rate on loans as 8\% per annum with
continouous compounding, and that interest is actually paid quarterly. From
equation (4.4) with $m = 4$ and $R_c = 0.08$, the equivalent rate with quarterly
compounding is

$$
4 \times (e^{0.08/4} - 1) = 0.0808
$$

or 8.08\% per annum. This means that on a \$1,000 loan, interest payments of
\$20.20 would be required each quarter.

# 4.5 Zero rates





## Example 4.3 - Calculating the forward rate agreement value

Suppose that the forward SOFR rate for the period between time 1.5 years and
time 2 years in the future is 5\% (with semiannual compounding) and that some
time ago a company entered into an FRA where it will receive 5.8\% (with
semiannual compounding) and pay SOFR on a principal of \$100 million for the
period. The 2-year (SOFR) risk-free rate is 4\% (with continuous compounding).
The value of the FRA is

$$
100,000,000 \times (0.058 - 0.050) \times 0.5 e^{-0.04 \times 2} = \$369,200
$$

---

## Example 4.4 - Calculating the bond price

For the bond in the following table, the bond price, $B$, is 94,213 and the
duration, $D$, is 2.653, so that equation (4.11) gives

$$
\Delta B = -BD \Delta y\tag{4.11}
$$

```{r example 4.4, echo=F}
time <- c(0.5, 1.0, 1.5, 2.0, 2.5, 3.0)
cash.flow <- c(5, 5, 5, 5, 5, 105)
present.value <- c(4.709, 4.435, 4.176, 3.933, 3.704, 73.256)
weight <- c(0.050, 0.047, 0.044, 0.042, 0.039, 0.778)
time.weight <- c(0.025, 0.047, 0.066, 0.083, 0.098, 2.333)
knitr::kable(data.frame(time, cash.flow, present.value, weight, time.weight),
             caption="Calculation of duration")
```

$$
\Delta B = -94.213 \times 2.653 \times \Delta y
$$

or

$$
\Delta B = -249.95 \times \Delta y
$$

When the yield on the bond increases by 10 basis points (=0.1\%),
$\Delta y = +0.001$. The duration relationship predicts that
$\Delta B = -249.95 \times 0.001 = -0.250$, so that the bond price goes down to
$94.213 - 0.250 = 93.963$. How accurate is this? Valuing the bond in terms of
its yield in the usual way, we find that, when the bond yield increases by 10
basis points to 12.1\%, the bond price is

$$
\begin{aligned}
5 e^{-0.121 \times 0.4} + 5 e^{-0.121 \times 1.0} + 5 e^{-0.121 \times 1.5}
  &+ 5 e^{-0.121 \times 2.0}\\
  &+ 5 e^{-0.121 \times 2.5} + 105 e^{-0.121 \times 3.0} = 93.963
\end{aligned}
$$

which is (to three decimal places) the same as that predicted by the duration
relationship.

---

## Example 4.5 - Calculating modified duration

$$
\Delta B = = B D^* \Delta y\tag{4.13}
$$

The bond in Table 1 has a price of 94.213 and a duration of 2.653. The yield,
expressed with semiannual compounding is 12.3673\%. The modified duration,
$D^*$, is given by

$$
D^* = \frac{2.653}{1 + 0.123673/2} = 2.499
$$

From equation (4.13),

$$
\Delta B = -94.213 \times 2.499 \times \Delta y
$$

or 

$$
\Delta B = -235.39 \times \Delta y
$$

When the yield (semiannually compounded) increases by 10 basis points (=0.1\%),
we have $\Delta y = +0.001$. The duration relationship predicts that we expect
$\Delta B$ to be $-235.39 \times 0.001 = -0.235$, so that the bond price goes
down to $94.213 - 0.235 = 93.978$. How accurate is this? An exact calculation
similar to that in the previous example shows that, when the bond yield
(semiannually compounded) increases by 10 basis points to 12.4673\%, the bond
price becomes 93.978. This shows that the modified duration calculation gives
good accuracy for small yield changes.

---

